### ISSUE TITLE
Client error:  Don't have access to requested journal: You don't have access

### ISSUE THREAD

**Issue by alex-vv** [alex-vv/clj#14]
when fetching pik-klakson community:

```
exec LJ.XMLRPC.getevents{:journal "pik-klakson", :selecttype "syncitems", :lastsync "1970-01-01 00:00:00", :get_video_ids true}
exec LJ.XMLRPC.getcomments{:journal "pik-klakson", :ditemid 648, :itemid 2, :extra true}
exec LJ.XMLRPC.getcomments{:journal "pik-klakson", :ditemid 1154, :itemid 4, :extra true}
exec LJ.XMLRPC.getcomments{:journal "pik-klakson", :ditemid 1522, :itemid 5, :extra true}
exec LJ.XMLRPC.getcomments{:journal "pik-klakson", :ditemid 897, :itemid 3, :extra true}
exec LJ.XMLRPC.getcomments{:journal "pik-klakson", :ditemid 1634, :itemid 6, :extra true}
exec LJ.XMLRPC.getcomments{:journal "pik-klakson", :ditemid 2802, :itemid 10, :extra true}
exec LJ.XMLRPC.getcomments{:journal "pik-klakson", :ditemid 3015, :itemid 11, :extra true}
exec LJ.XMLRPC.getcomments{:journal "pik-klakson", :ditemid 3185, :itemid 12, :extra true}
exec LJ.XMLRPC.getcomments{:journal "pik-klakson", :ditemid 4058, :itemid 15, :extra true}
exec LJ.XMLRPC.getcomments{:journal "pik-klakson", :ditemid 2523, :itemid 9, :extra true}
Client error:  Don't have access to requested journal: You don't have access
java.lang.Exception: Client error:  Don't have access to requested journal: You don't have access
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at clojure.lang.Reflector.invokeConstructor(Reflector.java:180)
	at clj.xmlrpc$xmlrpc.invokeStatic(xmlrpc.clj:22)
	at clj.xmlrpc$xmlrpc.invoke(xmlrpc.clj:16)
	at clj.xmlrpc$xmlrpc_challenge.invokeStatic(xmlrpc.clj:42)
	at clj.xmlrpc$xmlrpc_challenge.invoke(xmlrpc.clj:38)
	at clj.core$exec.invokeStatic(core.clj:17)
	at clj.core$exec.invoke(core.clj:13)
	at clj.core$get_comments.invokeStatic(core.clj:24)
	at clj.core$get_comments.invoke(core.clj:23)
	at clj.core$fetch_post_comments.invokeStatic(core.clj:104)
	at clj.core$fetch_post_comments.invoke(core.clj:99)
	at clj.core$run$fn__5574.invoke(core.clj:124)
```

**Comment by alex-vv** [comment]
this item is private and access to its comments is restricted, although for some reason it is available in `getevents` API call

**Comment by alex-vv** [comment]
now handling such case
